### ISSUE TITLE
希望deepin V20应用商店收录kindle for pc这款软件

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/deepin-app-store#4]
kindle for pc这款软件是看亚马逊购买的电子书的软件，如果wine的kindle for pc1.11或者其他版本的话效果还是比较好的，希望收录在应用商店里面
我现在就是自己安装winehq-devel来wine kindle for pc这款软件，但是现在发现winehq-devel和deepin-wine5-tools这款软件冲突了，每次重装系统都要重新安装winehq-devel也是麻烦，希望应用商店收录经量多的软件，让软件安装变得越来越方便

**Comment by widon1104** [comment]
希望应用商店收录尽可能多的软件，让用户自己去wine会出很多问题

**Comment by XMuli** [comment]
更多的新软件在逐渐适配中， 已经反馈

**Comment by widon1104** [comment]
使用deepin-wine5 wine kindle for pc1.11这款软件以后，软件能够启动，但是无法下载书籍，原生的wine没有这个问题
