### ISSUE TITLE
有时候我已经下载了这个软件确无法评论

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/deepin-app-store#6]
### 我已经下载了
它叫我先下载再评论，可是我已经下载了，就很~~恼火~~

**Comment by XMuli** [comment]
自带软件？

**Comment by Decodetalkers** [comment]
> 自带软件？

商店下的，不能评论出现在我在终端更新过它就认为我没有下了，但是在打开那个按钮它又认为我下载了

另一个是我从商店源下载出现

反正应用界面在是否下载标签它认为我下载了，但是评论资格又认为我没有下载

**Comment by XMuli** [comment]
~~此类问题， 你可以去社区论坛交流， 这种使用的产品设计，或者用户体验。我不是很清楚~~

帮询问过了。 需要登录账号下载才能评论; 如果是下载之后再登录账号，则评论不了； 只能说是设计如此。
